name: Github Actions demo
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Hello
        run: echo "Hello world"
      - name: Printing  Goodbye
        run: echo "Bye bye"
